services:
  proxy-server:
    image: localhost:5000/velocity
    ports:
      - "25565:25577/tcp"
      - "25565:25577/udp"
    volumes:
      - ./velocity/configs/proxy:/proxyconfig
  lobby-server:
    image: localhost:5000/papermc
    expose:
      - "25565/tcp"
      - "25565/udp"
    volumes:
      - ./papermc/configs/lobby:/serverconfig
      - lobby_world:/paper/world
  survival-server:
    image: localhost:5000/papermc
    expose:
      - "25565/tcp"
      - "25565/udp"
    volumes:
      - ./papermc/configs/survival:/serverconfig
      - survival_world:/paper/world
      - survival_nether:/paper/world_nether
volumes:
  lobby_world:
  survival_world:
  survival_nether:

