services:
  proxy-server:
    image: localhost:5000/velocity
    ports:
      - "25565:25577/tcp"
      - "25565:25577/udp"
    volumes:
      - ./velocity/configs/proxy:/proxyconfig
  lobby-server:
    image: localhost:5000/papermc
    expose:
      - "25565/tcp"
      - "25565/udp"
    volumes:
      - ./papermc/configs/lobby:/serverconfig
  survival-server:
    image: localhost:5000/papermc
    expose:
      - "25565/tcp"
      - "25565/udp"
    volumes:
      - ./papermc/configs/survival:/serverconfig

